create table SNH48(
   name VARCHAR(100) NOT NULL,
   pinyin VARCHAR(100) NOT NULL,
   room_id VARCHAR(100) NOT NULL,
   member_id VARCHAR(100) NOT NULL,
   group_id VARCHAR(100) NOT NULL,
   sid VARCHAR(100) NOT NULL,
   gid VARCHAR(100) NOT NULL,
   gname VARCHAR(100) NOT NULL,
   abbr VARCHAR(100) NOT NULL,
   tid VARCHAR(100) NOT NULL,
   tname VARCHAR(100) NOT NULL,
   pid VARCHAR(100) NOT NULL,
   pname VARCHAR(100) NOT NULL,
   nickname VARCHAR(100) NOT NULL,
   join_day VARCHAR(100) NOT NULL,
   height VARCHAR(100) NOT NULL,
   birth_day VARCHAR(100) NOT NULL,
   star_sign_12 VARCHAR(100) NOT NULL,
   star_sign_48 VARCHAR(100) NOT NULL,
   birth_place VARCHAR(100) NOT NULL,
   speciality VARCHAR(100) NOT NULL,
   hobby VARCHAR(100) NOT NULL,
   catch_phrase VARCHAR(1000) NOT NULL,
   weibo_id VARCHAR(100) NOT NULL,
   weibo_verifier VARCHAR(100) NOT NULL,
   blood_type VARCHAR(100) NOT NULL,
   status VARCHAR(100) NOT NULL,
   PRIMARY KEY ( sid )
);